### PR TITLE
alot of small fixes

### PR DESCRIPTION
**Pull request by Cosmella-v**
**Contents of commits:**

- Added a integrity function
- Fix dual click bug
- Make node ids not required (Ofc it does use it if it is installed)
- Do something to do with jumping to make it so you can only release if you have clicked first
- Make one channel per cube so it doesn't lag as much
- Pause bug fix (Mac)
- Comments

### CODE REVIEW

**Comment by BeatACVR** [comment]
integraty

**Comment by BeatACVR** [comment]
when i accept this, im not going to know how to update cs lite anymore lol

**Comment by Cosmella-v** [comment]
you can merge it i'm done my epic bug fix sesson

**Comment by BeatACVR** [comment]
okay. one more thing, would make sense if 'only on jump' was done in integrity i think

**Review by BeatACVR — APPROVED** [review]
thamnsk

**Pull request merged**
